from enum import Enum

class Site(Enum):
    All = "all"
    News = "news"
    Nasional = "nasional"
    Regional = "regional"
    Megapolitan = "megapolitan"
    Global = "global"
    Tren = "tren"
    Health = "health"
    Food = "food"
    Edukasi = "edukasi"
    Money = "money"
    UMKM = "umkm"
    Tekno = "tekno"
    Lifestyle = "lifestyle"
    Homey = "homey"
    Properti = "properti"
    Bola = "bola"
    Travel = "travel"
    Otomotif = "otomotif"
    Sains = "sains"
    Hype = "hype"
    JEO = "jeo"
    Skola = "skola"
    Stori = "stori"
    Konsultasi_Hukum = "konsultasihukum"
    Wiken = "wiken"
    Indeks_Headline = "headline"
    Indeks_Terpopuler = "terpopuler"
    Indeks_Sorotan = "sorotan"
    Indeks_Topik_Pilihan = "topik-pilihan"
    Indeks_Advertorial = "advertorial"